### ISSUE TITLE
Avoid monkeypatching/action at a distance

### ISSUE THREAD

**Issue by steimelchrome** [WICG/document-picture-in-picture#10]
Migrated from https://github.com/steimelchrome/steimelchrome.github.io/issues/8

From domenic@:

"
Your spec includes two normative monkeypatches (see [W3C TAG design principles](https://w3ctag.github.io/design-principles/#monkey-patching) and [Anne's blog](https://annevankesteren.nl/2014/02/monkey-patch) for more on why this is bad):

https://steimelchrome.github.io/draft_spec.html#one-pip-window monkeypatches other parts of the spec, with a normative "must" requirement. Instead, that requirement needs to be incorporated (and made precise---what are "appropriate events"??) in the place where picture-in-picture statuses change.

https://steimelchrome.github.io/draft_spec.html#relative-urls monkeypatches the entire web platform's URL resolution. This is quite bad! And probably not what you intended. I suspect instead you want to create the new browsing context / Window / Document with an overridden base URL of some sort.
"

**Comment by domenic** [comment]
Looks pretty good. #63 is a followup, but that's not on you. For "One PiP Window", I'd suggest just adding a pointer to make things very explicit. Something like:

> This flexibility is expressed as a step inside the requestWindow() method steps."
