### ISSUE TITLE
Speech-to-Text quality heavily affected when Pip is active

### ISSUE THREAD

**Issue by pandyama** [WICG/document-picture-in-picture#100]
If there is an active audio recording with Pip active, the transcript quality is significantly impacted. 

Has this been a limitation of Pip from the beginning? 
Or did something get pushed in recent changes that could have impacted this?

**Comment by steimelchrome** [comment]
Do you have repro steps available? If you could create a bug on issues.chromium.org with repro steps that would be ideal

**Comment by steimelchrome** [comment]
Actually, this is probably related to https://issues.chromium.org/issues/40276131, which was rolled back around this time and then relanded. I'll close this as fixed for now but feel free to reopen if there's still an issue

**Comment by pandyama** [comment]
thanks @steimelchrome
