### ISSUE TITLE
[Bug]: Cursor doesn't change on initial render

### ISSUE THREAD

**Issue by GoodluckH** [WICG/document-picture-in-picture#106]
Using this example: https://lazy-guy.github.io/tomodoro/index.html

When you toggle the PiP, and hover your mouse over any button in the PiP window. The cursor doesn't change to a pointer type immediately. 

It only changes after clicking outside of the PiP then hovering back in.

[MacOS, Chrome]

**Comment by steimelchrome** [comment]
I tried this on Chrome 120.0.6099.71 (stable) and 122.0.6180.0 (canary) on macOS Sonoma 14.1.2. Both of them seemed to work fine. Which version of Chrome is this?

**Comment by GoodluckH** [comment]
This is 119.0.6045.199 (Official Build) (arm64)

**Comment by steimelchrome** [comment]
Oh okay. There was a change that landed in 120.0.6091.0 that I think may have incidentally fixed the issue, so let me know if you can reproduce after that version

**Comment by GoodluckH** [comment]
Awesome! The bug is gone. Btw, do you guys have any messaging groups for discussing the PIP development? 

We'll be pushing Document PiP to our production app very soon (next week), and would like to work closely with you guys to provide feedback.
