### ISSUE TITLE
[Bug] Resize doesn't work on PiP

### ISSUE THREAD

**Issue by GoodluckH** [WICG/document-picture-in-picture#107]
I'm building a React project and in my code, I have `pipWindow.resizeBy(20, 20)`. 

However, this simply doesn't work.

I also tried to do that directly in the console window in the DevTool, also doesn't work.

In my code, if I do `window.resizeBy(..)`, it will change the parent window's size, but not the PiP window.

[MacOS, Chrome 120]

**Comment by steimelchrome** [comment]
Chrome's implementation of allowing resizeTo/resizeBy via a user gesture is launching in M121. Let me know if you can't get this to work in Chrome 121.0.6157.0 or later (that's the initial version that has the resizing allowed)
