### ISSUE TITLE
[Spec] Clarification on "top-level traversable"

### ISSUE THREAD

**Issue by GoodluckH** [WICG/document-picture-in-picture#108]
I was making a change MDN's documentation (See https://github.com/mdn/content/pull/31016) on the Document PiP API by adding this:

`The Picture-in-Picture window is limited to one per website at a time, with the user agent potentially further restricting the global number of Picture-in-Picture windows open.`

Since the PR was opened, there had been a few conversations on whether "website" is the correct language to mirror what the [spec](https://wicg.github.io/document-picture-in-picture/#one-pip-window) says: "However, whether only one window is allowed in Picture-in-Picture mode across all [top-level traversables](https://html.spec.whatwg.org/multipage/document-sequences.html#nav-top)"

Would be helpful if anyone who authored the spec to clarify what "top-level traversables" mean. Are they browser tabs, origins, etc.?

**Comment by steimelchrome** [comment]
A top-level traversable is a browser tab
