### ISSUE TITLE
Style sheet copying

### ISSUE THREAD

**Issue by steimelchrome** [WICG/document-picture-in-picture#12]
Migrated from https://github.com/steimelchrome/steimelchrome.github.io/issues/10

From domenic@:

"
The style sheet copying text currently says:

the [CSS style sheet](https://drafts.csswg.org/cssom-1/#css-style-sheet)s applied the current [associated Document](https://html.spec.whatwg.org/multipage/window-object.html#concept-document-window) should be copied and applied to the target browsing context’s [associated Document](https://html.spec.whatwg.org/multipage/window-object.html#concept-document-window).

First, I suspect "should" is not intended here (i.e., the behavior is not optional).

Second, there often is more than one CSS style sheet applied to a document. There can be many, in fact: some from <style>, some from <link>, some from adoptedStyleSheets... Which ones do you want to copy? As per https://github.com/steimelchrome/steimelchrome.github.io/issues/6, you need to navigate to each of these collections in a precise manner, and gather up the appropriate objects to copy over.

Third, what exactly are the appropriate objects to copy over, and what does copying mean? Are you going to insert a <style> for each source <style>, a <link> for each source <link>, etc.? What if some of them failed to load? Are you going to copy over the text exactly, including e.g. syntax errors and exact whitespace, or will you instead copy over some serialization and then deserialize it? All of these things are observable.
"

**Comment by steimelchrome** [comment]
I've fixed "First" and "Second", though I have not yet figured out how we should define copying for "Third"

**Comment by domenic** [comment]
I had a suggestion for how to do this, but it was jumping too quickly to a solution. I've encapsulated it in a `<details>` below.

Instead, I'd love to get your thoughts on the questions I posed in the OP for "Third". And, what does the implementation do currently?

<details>
<summary>Original opinionated comment</summary>

I think the way to do it is, switch from "add a CSS style sheet", to ["create a CSS style sheet"](https://drafts.csswg.org/cssom/#create-a-css-style-sheet). (Which is... not well-named.)

Unfortunately these algorithms are not very explicit about their inputs, so we just kinda have to do our best. I think to do that, you need to specify all the properties listed below https://drafts.csswg.org/cssom-1/#css-style-sheet , from "type" through "stylesheet base URL".

Obviously, most of them will just be copies of the original's. But for some of them we have to be careful:

- parent CSS style sheet + owner CSS rule: you can't have cross-document parents. So I guess you'd have to find the corresponding newly-copied parent, and change this? Maybe in a post-copying pass, once all of them have been created? Or maybe we can null these out, without significant consequences?

- owner node: you don't want to point to the original owner node in the owner document, I am pretty sure. So null this out? Then it won't show up in `document.styleSheets`, which seems good.

- media: you don't want to point to the same literal `MediaList` object, so I guess you want to create a new MediaList object given the old one's mediaText attribute?

- CSS rules: pointing to the exact same CSS rules seems bad, as then mutations in one window will affect the other. But these aren't super well-defined data structures (or at least, their definitions are not linked from "CSS rules"). So maybe we can just say something like "a deep copy of _original_'s CSS rules" and hope that's enough...

</details>

**Comment by steimelchrome** [comment]
This is what we currently do:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/document_picture_in_picture/picture_in_picture_controller_impl.cc;l=407;drc=0ac0497cb5ca4d7682614ab5e3c1ec646d8016a9

We loop through the document's stylesheets (which doesn't include the adopted style sheets) and create a copy of the StyleSheetContents and then inject that into the document. I didn't write this personally but I asked the person who did and their understanding is that StyleSheetContents is already parsed

**Comment by steimelchrome** [comment]
The resulting background color is blue in that case. The stylesheet is not listed in document.styleSheets (nor in document.adoptedStyleSheets), and in DevTools the rules are listed as coming from an "injected stylesheet" similar to how it indicates rules from "user agent stylesheet"s

<img width="641" alt="devtools screenshot" src="https://github.com/WICG/document-picture-in-picture/assets/78613055/a3aa0b04-8d0b-409c-9ed5-834153096f42">

Given that it's not in document.styleSheets/adoptedStyleSheets and therefore not in [document or shadow root css style sheets](https://drafts.csswg.org/cssom/#documentorshadowroot-document-or-shadow-root-css-style-sheets) or [final css style sheets](https://drafts.csswg.org/cssom/#documentorshadowroot-final-css-style-sheets), I'm not exactly sure what we'd say here.

**Comment by domenic** [comment]
That is troubling. It seems like we'd need to do a good deal of specification work to introduce this new "injected stylesheets" concept. I don't have a lot of experience with that; @tabatkins is probably the best equipped to suggest how to do that.

It might be worth taking a step back and asking if this feature is really necessary? Do we have strong partner feedback that they would be unable to build their desired experiences manually, e.g. by inserting their own stylesheets? It seems like emulating the stylesheet copying process in JavaScript shouldn't be too hard for pages to do themselves, if that's what they really want.

**Comment by steimelchrome** [comment]
Good points. We discussed this internally and came to the conclusion that removing it was our best option
