### ISSUE TITLE
doctype missing

### ISSUE THREAD

**Issue by alin1771** [WICG/document-picture-in-picture#127]
the PiP document is using quirks mode by default because HTML5 doctype is missing
please add `<!DOCTYPE html>`
or an option for it in DocumentPictureInPictureOptions

**Comment by steimelchrome** [comment]
Thanks for bringing this up! I've updated the spec to copy the compatibility mode of the opener document.

The actual Chrome code change is here: crrev.com/c/5900737. Assuming it lands soon, it'll be released in Chrome 131

**Comment by yume-chan** [comment]
I just ran into this issue.

Before it gets fixed, I found https://stackoverflow.com/a/4494144 works:

```js
const pipWindow = await documentPictureInPicture.requestWindow({
  width,
  height,
});

console.log(pipWindow.document.compatMode); // BackCompat

pipWindow.document.open();
pipWindow.document.write("<!doctype html>");
pipWindow.document.close();

console.log(pipWindow.document.compatMode); // CSS1Compat
```
