### ISSUE TITLE
documentPictureInPicture.requestWindow() should reject from a PiP window

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/document-picture-in-picture#13]
I believe spec should say that `documentPictureInPicture.requestWindow()` MUST reject with `"NotAllowedError"` when invoked from a PiP window as introduction says the PiP window cannot open more windows.

![image](https://user-images.githubusercontent.com/634478/203978676-71c65a19-9b01-4c7d-a6ec-6fe284b43655.png)

**Comment by steimelchrome** [comment]
Fixed
