### ISSUE TITLE
Security considerations

### ISSUE THREAD

**Issue by hemeryar** [WICG/document-picture-in-picture#15]
Hi! This proposal ended up in the Chromium security&privacy triage queue, and I had a look at it.

I'm a bit concerned about the potential of this proposal to bypass security directives. This might have to replicate all the inheritance mechanisms used by popups initial empty documents. Examples include sandboxing, Permissions Policy, COOP, etc.

Third party iframes opening popups have also been a security nightmare in the past, and the feature should probably be completely off for them.

Thanks,
Arthur

**Comment by hemeryar** [comment]
Just to be clear: if we spec this feature as technically following all the steps of a popup, we should be fine security wise and avoid duplicating entry points.

**Comment by steimelchrome** [comment]
The feature is turned off for third-party iframes
