### ISSUE TITLE
Add a "considered alternatives" section to the explainer?

### ISSUE THREAD

**Issue by yoavweiss** [WICG/document-picture-in-picture#18]
WebKit folks [raised questions](https://github.com/WebKit/standards-positions/issues/41#issuecomment-1233271770) around `window.open` that I know I had reading this for the first time. It might be worthwhile to add a section to the explainer outlining why this is not the approach picked, and its downsides.

**Comment by Jaifroid** [comment]
Issue could be closed, as there is now such a section.
