### ISSUE TITLE
`initialAspectRatio` should size window contents

### ISSUE THREAD

**Issue by mister-ben** [WICG/document-picture-in-picture#25]
Setting the aspect ratio is important for content that has a natural aspect ratio, like a video.

The value of `initialAspectRatio` (or `width` and `height`) currently sizes the complete outer window, including its title bar, resulting in a window too wide for the content. The title bar height could vary by OS, font settings, locale, and eventually browser.

Users using picture-in-picture generally want to move the video out of the way of something else to multitask. Having an inappropriately sized window displaying black padding around the video will be an annoyance.

The window should be sized so that the window content is the requested aspect ratio; the browser can determine on the overall size of the window accommodating title bar within whatever constraints or preferences apply.

**Comment by steimelchrome** [comment]
Thanks for the issue. This bug is already being tracked in crbug.com/1407629

**Comment by steimelchrome** [comment]
Closing as initialAspectRatio was removed from the spec a while ago
