### ISSUE TITLE
Possible to open multiple pip windows?

### ISSUE THREAD

**Issue by amoghasgekar** [WICG/document-picture-in-picture#27]
I noticed that every call to the window.documentPictureInPicture.requestWindow creates a new pip window but destroys the previous one. Is that intentional? Is there a way to create multiple windows?

**Comment by tomayac** [comment]
The [spec certainly allows it](https://wicg.github.io/document-picture-in-picture/#one-pip-window), and browser makers can decide what to do. As far as I can tell, the current implementation I could test in Chrome on macOS allows just one PiP window at a given time.

**Comment by amoghasgekar** [comment]
You're right! Thanks for catching that, just submitted feedback to the chrome team. I'm on Chrome on Linux and that's where I see a single pip window.

**Comment by hanguokai** [comment]
This makes me a little worried about the stability of this function. The current implementation supports only one pip window. If another website (that not under my control) also uses this feature, then my pip window will be forced to close.

**Comment by steimelchrome** [comment]
Closing as the spec does allow this, so it's more of a feature request for Chrome's implementation. That request is tracked at https://issues.chromium.org/issues/40891176
