### ISSUE TITLE
Move pip window to current virtual desktop

### ISSUE THREAD

**Issue by opusonline** [WICG/document-picture-in-picture#33]
Thanks for bringing such great features to the web!
I'm a web developer and I would love to use the document pip feature, but there's one major disadvantage compared to video-pip windows. As a mac user I'm used to work with virtual desktops and the video pip-window is always shown on the current virtual desktop. Unfortunately, the document-pip window does not follow along, it just stays at the virtual desktop where it was opened. That makes no sense to me. The main purpose of such a window is to be always present to the user. With the current behaviour, it is just an advanced popup window.
I would love to see a requirement in the spec saying that it must be always visible to the user and therefor be present on the current active desktop.
Thanks in advance!

**Comment by steimelchrome** [comment]
Hi Stefan,

This was actually a bug in the Chrome implementation, but it should be fixed in 114.0.5696.0 and later.

I'll look into what language we need in the spec to make this a requirement, thanks for the suggestion!

**Comment by opusonline** [comment]
Thanks for your feedback!
I have tested in Chrome Canary today and it works great!
