### ISSUE TITLE
Make spec available in  https://wicg.github.io/document-picture-in-picture

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/document-picture-in-picture#4]
It would be good go to have index.bs file processed and available as an HTML page in https://wicg.github.io/document-picture-in-picture the way all other WICG repo work.

@steimelchrome Is that planned?

For now, it seems like we only have https://steimelchrome.github.io/draft_spec.html

**Comment by steimelchrome** [comment]
Yep, I'm hoping to get that working this week
