### ISSUE TITLE
"is a DocumentPictureInPicture Window" is not well-defined

### ISSUE THREAD

**Issue by domenic** [WICG/document-picture-in-picture#41]
It sounds like the model here is that every `Window` has a boolean, "is document picture-in-picture", which is either true or false, false by default. Or maybe it should belong to a navigable instead? Or a top-level traversable?

Then you should check that boolean.

**Comment by domenic** [comment]
A similar problem shows up a few steps later:

> close any existing DocumentPictureInPicture [Window](https://html.spec.whatwg.org/multipage/nav-history-apis.html#window)s or [PictureInPictureWindow](https://w3c.github.io/picture-in-picture/#pictureinpicturewindow)s.

I'm not sure why there are two separate concepts here... I think there's just one, right?

**Comment by steimelchrome** [comment]
There's actually two types of picture-in-picture windows:

1) Document Picture-in-Picture windows, which are being defined and created in this spec

2) [PictureInPictureWindow](https://w3c.github.io/picture-in-picture/#pictureinpicturewindow)s defined and created in a [different spec](https://w3c.github.io/picture-in-picture/) that display only video content and are created via HTMLVideoElement's requestPictureInPicture() method
