### ISSUE TITLE
"close any existing picture-in-picture windows" probably more complicated than it needs to be?

### ISSUE THREAD

**Issue by domenic** [WICG/document-picture-in-picture#62]
[close a top-level traversable](https://html.spec.whatwg.org/#close-a-top-level-traversable) invokes [unload a document](https://html.spec.whatwg.org/#unload-a-document), which invokes [unloading document cleanup steps](https://html.spec.whatwg.org/#unloading-document-cleanup-steps), which invokes the [exit picture-in-picture algorithm](https://w3c.github.io/picture-in-picture/#exit-picture-in-picture-algorithm).

The call to "unload a document" is recursive, as well.

So, I think steps 2-3 of "close any existing picture-in-picture windows" are not needed.

**Comment by steimelchrome** [comment]
"close any existing picture-in-picture windows" closes any existing Document Picture-in-Picture windows *and* any vidoe Picture-in-Picture windows. Step 1 closes the Document Picture-in-Picture windows, Step 2 closes video Picture-in-Picture windows in top-level documents, and step 3 does the same for non-top-level documents.

**Comment by domenic** [comment]
Got it! I guess that is pretty clear now that I re-read.
