### ISSUE TITLE
Relative URL confusion tracking issue

### ISSUE THREAD

**Issue by domenic** [WICG/document-picture-in-picture#63]
In https://github.com/WICG/document-picture-in-picture/issues/10 we discussed relative URL resolution. You said

> I was able to just remove the relative URLs section since that is actually taken care of for free by the "creating a new auxiliary browsing context and document" algorithm.

I checked and... I think you're right? But, the HTML spec's behavior doesn't seem to match any browsers?? I filed https://github.com/whatwg/html/issues/9310 to track the potential HTML spec bug.

So, either HTML has a bug, and fixing it will break this spec. (I.e., it will mean that document PiP windows get an `about:blank` base URL instead of your desired inherited base URL.) Or, there's something subtle about HTML that we both missed, and this spec is currently broken.

I suspect what we'll have to do here is monkeypatch https://html.spec.whatwg.org/#fallback-base-url to have a case for checking if document's navigable is a document-picture. (See https://github.com/w3ctag/design-principles/pull/441 for some in-progress guidance on how to do that well, from this spec.) But probably first we need to resolve my confusion about what HTML says...

**Comment by steimelchrome** [comment]
I think this currently disabled-by-default feature in Chromium might be the behavior from the spec:

https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:third_party/blink/common/features.cc;l=1596;drc=004227a1fc7355a9080146c2621d072bd2327701

**Comment by domenic** [comment]
I think you're right. And furthermore, as discussed in https://github.com/whatwg/html/issues/9310#issuecomment-1571668422 , the plan is to converge on something (close to) the spec behavior.

I would suggest making this super-clear by adding a note like the following as part of the step that calls "[creating a new top-level traversable](https://html.spec.whatwg.org/#creating-a-new-top-level-traversable)":

```
The resulting {{Document}}'s [=Document/URL=] will be `about:blank`, but its [=document base URL=] will fall back to be that of the initiator that called {{DocumentPictureInPicture/requestWindow()}}. Some browsers do not implement this fallback behavior for normal `about:blank` popups; see <a href="https://github.com/whatwg/html/issues/421">whatwg/html#421</a> for discussion. Implementers are advised to make sure this inheritance happens as specified for document picture-in-picture windows, to avoid further interop problems.
```
