### ISSUE TITLE
"The PiP window cannot be navigated" is not specified

### ISSUE THREAD

**Issue by domenic** [WICG/document-picture-in-picture#65]
I only found this by accident by reading the non-normative introduction:

> The PiP window cannot be navigated (any `window.history` or `window.location` calls that change to a new document will close the PiP window).

Is this still intended to be implemented? If so, we've got some fun ahead of us, figuring out how to spec it. Some questions to answer:

- Are same-document navigations, e.g. `history.pushState()` or `location.hash = "foo"`, OK?
- What about navigations that target a `Content-Disposition: attachment` or status-code 204/205 destination? Those never actually move to a new document. (But, we only find out after doing a network round trip.)

**Comment by steimelchrome** [comment]
Yes, so in Chrome we allow same-document navigations, but other navigations will result in closing the document PiP window. I believe that means we'd also close in the situations you describe in the second bullet point

**Comment by steimelchrome** [comment]
Specifically, here is the code that closes the window on navigation:

https://source.chromium.org/chromium/chromium/src/+/main:content/browser/picture_in_picture/document_picture_in_picture_window_controller_impl.cc;l=206;drc=0195cc9b83ebca340aee0a8404ab356cdc5b1d5b

**Comment by domenic** [comment]
OK, great, that makes sense. Then, I would suggest adding a monkeypatch section to the spec which happens as part of the task queued in step 16.3 of https://html.spec.whatwg.org/#navigate .

**Comment by steimelchrome** [comment]
I think this should be fixed, but let me know what you think about it. If it looks good, I can open an issue to merge the monkeypatch

**Comment by domenic** [comment]
This doesn't quite suffice, although it's close. What will happen now is:

- The spec for something like `location.href` runs
- It calls the "navigate" algorithm
- We reach step 16.3 in the navigate algorithm, which posts a task to abort the current document
- We continue onward to step 16.4 etc.
- Eventually the posted task happens, and then we try to close the PiP window which is currently in the process of navigating. This probably causes some sort of "spec crash".

We need to actually abort the navigation process, similar to what step 16.2 in navigation does.
