### ISSUE TITLE
"The PiP window will never outlive the opening window" is not specified

### ISSUE THREAD

**Issue by domenic** [WICG/document-picture-in-picture#66]
I found this by chance reading the non-normative introduction.

What exactly is meant by "opening window"? Is it the exact `Window` object, so e.g. if I navigate the opener from one page to a different one, the PiP window should close? Or is it the navigable (~ browser tab), so I could go across multiple pages and keep the PiP window open? Or something in between?

**Comment by steimelchrome** [comment]
I think this should be fixed, but let me know what you think about it. If it looks good, I can open an issue to merge the monkeypatch

**Comment by domenic** [comment]
A few things:

- You probably want to patch "destroy" instead of "abort". "abort" is called from "stop loading", which is invoked by the browser stop button, `window.stop()`, and `document.open()`.

- As mentioned in https://github.com/WICG/document-picture-in-picture/issues/44. Your use of "close" means that beforeunload handlers will run, and will potentially pop up dialogs saying "are you sure you want to close this page?". Which could result in the PiP window not being closed. Is that the intent?
  - If the intention is to skip both beforeunload and unload events, you can go straight to "destroy".
  - If the intent is to skip beforeunload events but not unload events, you'll need a custom algorithm that does the last two steps of "close".
  - If the intent is to fire both events, but never pop up a dialog, then continuing to use "close" is good, but you should monkeypatch in a clause to the bulleted list in https://html.spec.whatwg.org/#checking-if-unloading-is-user-canceled which prevenst the unload prompt from being shown in PiP windows.
  - An alternate architecture might be to patch "close" to add the PiP window to "toUnload" (either before step 1, if you want to fire beforeunload, or after step 2, if you want to only fire unload). Then, patch "destroy" to include the destruction of the PiP window.

- This only closes the last-opened PiP window. Is it OK for all the others to stick around?

**Comment by steimelchrome** [comment]
Okay I landed a few things for this:
1) We now patch "destroy" instead of "abort" (#74)
2) The intent is to skip beforeunload events. Instead of using a custom algorithm, I instead monkeypatch the close algorithm itself since no calls to close should fire the beforeunload event for document pip windows. Let me know what you think about that patch (#75)
3) My answer to your last point was going to be "there's only one PiP window", but I realized we never specified that you could only have one document PiP window per top-level traversable. So I added clarification that while we don't restrict the number of document PiP windows globally, a top-level traversable can only have one (#73)

**Comment by domenic** [comment]
This looks great! I'm happy to close this.

A minor note: I think the dance of checking win's closed attribute before calling close is a bit awkward, and ideally unnecessary. But that should probably be handled on the HTML side. I'll work on that, maybe. In the meantime it's clear enough as-is :)

**Comment by steimelchrome** [comment]
I'm actually not sure about this anymore. I think if we only patch destroy and not abort, then the opener document can navigate without destroying the opener document, and so we wouldn't close the pip window even though we should. So maybe we need to patch destroy and navigate

**Comment by domenic** [comment]
I think that's #65 :)

**Comment by steimelchrome** [comment]
Sort of. #65 is about when the PiP window itself navigates, and this is about when the page that opened the PiP window navigates. Either way, I fixed both in the same patch
