### ISSUE TITLE
Support invoking "back to tab" programmatically 

### ISSUE THREAD

**Issue by drmercer** [WICG/document-picture-in-picture#94]
In the header of the Document PIP window in Chrome, there's a "back to tab" button that both (1) closes the PIP window and (2) focuses the owning window/tab in the browser.

It would be nice to be able to programmatically invoke that action in response to a user gesture in the PIP window. For example, in a task management app that shows you your current task, the PIP window might want an "adjust my plan" button that takes you back to the main tab.

**Comment by GoodluckH** [comment]
This is a great suggestion for improving the end user experience. "Back to tab" communicates weaker than "Adjust my plan".

Would love to see this get implemented.
